### ISSUE TITLE
Dutch language

### ISSUE THREAD

**Issue by ReD1470** [ngnijland/MMM-text-clock#1]
1st off, great work, and wondering if you have gotten around to make the dutch translation?
I have different version, but the translations is a bit of

kind regards ReD

**Comment by ngnijland** [comment]
Hi ReD,

Hopefully I'll have time this week to take a look into translations!

I think I want to extract the `letters` arrary, the `wordMap` array and the `getActiveWords` function into separate files in a `locale` folder. Then based on the language of the MagicMirror config use the entities needed for the given language with a fallback to English.

Also the amount of letters displayed horizontally in the grid should be variable as it can be different for different languages.

Any thoughts on this?

Regards,
Niek

**Comment by ngnijland** [comment]
@ReD1470 I've added the Dutch translation.

Feel free to reopen this issue or open a new one for any questions or feature requests!

**Comment by ReD1470** [comment]
YEAH BABY!! tnx.
________________________________
Van: Niek <notifications@github.com>
Verzonden: dinsdag 19 mei 2020 23:00
Aan: ngnijland/MMM-text-clock <MMM-text-clock@noreply.github.com>
CC: John <jvdgijp@outlook.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [ngnijland/MMM-text-clock] Dutch language (#1)


@ReD1470<https://github.com/ReD1470> I've added the Dutch translation.

Feel free to reopen this issue or open a new one for any questions or feature requests!
