### ISSUE TITLE
Multiple instances of MMM-text-clock compete on the SET_LANGUAGE notification

### ISSUE THREAD

**Issue by pierrephi** [ngnijland/MMM-text-clock#11]
This is a side effect of the new language alternation feature :/

My config is as follows to allow for different layouts depending on the page I display, the problem is that the node_helper.js is global to all instances of the module as documented in [this page](https://docs.magicmirror.builders/development/node-helper.html#module-instance-methods)

> Note: Since all instances of your module will receive the notifications, it's your task to make sure the right module responds to your messages.

As a result both instances compete on the language list and the alternationTimeInterval if they are different and when they are the same, double notifications are happening.

```
		{
			module: "MMM-text-clock",
			classes: "text-clock-homescreen",
			position: "middle_center",
			config: {
				compact: false,
				size: "large",
				language: ['ar','fr','en','es','jp'],
				languageAlternationInterval: 10
			}
		}, 
		{
			module: "MMM-text-clock",
			classes: "text-clock-small",
			position: "bottom_bar",
			config: {
				compact: true,
				size: "medium",
				language: ['fr','en'],
				languageAlternationInterval: 1
			}
		}, 
		{
			module: 'MMM-pages',
			config: {
				modules:
				[[ "text-clock-homescreen"], 
				[ "clock", "currentweather", "newsfeed", "weatherforecast", "newsfeed",  "calendar", "text-clock-small"]],
				fixed: ['alert', 'updatenotification', "MMM-page-indicator"],
				homePage: 0,
				rotationHomePage: 180000,
				animationTime: 1000,
				rotationTime: 120000
				}
		},

```

Logging this issue to keep track of it for now, will look at how to best solve it when I have some time.

**Comment by ngnijland** [comment]
Ah, good catch! Maybe we can generate a random string that will be unique for each instance and then validate it in the notification receiver? Maybe we can even check if there are multiple instances of the same module and only do it in that scenario 🤔 I don't know if MagicMirror has any functionality for this.

**Comment by pierrephi** [comment]
the default calendar module was updated to behave correctly in this scenario , I will inspire from this implementation

**Comment by pierrephi** [comment]
```
		this.sendSocketNotification("ADD_CALENDAR", {
			id: this.identifier,   <===
			url: url,
			excludedEvents: calendarConfig.excludedEvents || this.config.excludedEvents,
			maximumEntries: calendarConfig.maximumEntries || this.config.maximumEntries,

```

```
// Override socket notification handler.
	socketNotificationReceived: function (notification, payload) {
		if (this.identifier !== payload.id) {.  <===
			return;
		}

```

**Comment by ngnijland** [comment]
👌
