### ISSUE TITLE
12:25 is displayed as 12:15 for the Dutch language

### ISSUE THREAD

**Issue by ngnijland** [ngnijland/MMM-text-clock#16]
When I checked the time at 12:25 the text spelled: "Het is kwart over twaalf" while it should have spelled "Het is vijf voor half een"

**Comment by oanstein** [comment]
I did a fix in https://github.com/ngnijland/MMM-text-clock/pull/17

**Comment by ngnijland** [comment]
Appreciate it @oanstein !
