### ISSUE TITLE
Display minutes progression for more accurate time display

### ISSUE THREAD

**Issue by pierrephi** [ngnijland/MMM-text-clock#22]
When the text clock is the only thing displayed on the mirror it is nice to have additional precision and display the minutes past the time that is displayed.

This involves changing the rounding algorithm to the lower 5 minute increment and display dots at the corner past that time e.g. 17:32 isHALF PAST FIVE and 2 dots

This would look like this:
![clockdots](https://user-images.githubusercontent.com/139273/122430068-90b73500-cf93-11eb-803d-46c7ed5f3ca8.jpg)

I am implementing it and the way I chose to do this is by extending the grid by one cell all around the clock to position the dots at the corners like so.
![dot grid](https://user-images.githubusercontent.com/139273/122430413-df64cf00-cf93-11eb-818b-0136ad7878d8.jpg)

Tell me if you are interested that I push this change once stabilised :)

**Comment by ngnijland** [comment]
Sure! I think that is a good addition. Can you make sure that users are able to opt-in or opt-out via the config?

**Comment by pierrephi** [comment]
Most definitely I have a config parameter for that. I continue the testing on my mirror and will push it mid week probably

**Comment by volobig** [comment]
Hello,

Have you implemented the functionality? If I go to your repo it seems to be the same without minutes right?

Could you please help me? I need the minutes hehe. thanks!!
