### ISSUE TITLE
Minutes for the clock

### ISSUE THREAD

**Issue by volobig** [ngnijland/MMM-text-clock#33]
Hi, I hope you are well.
Sorry to bother you but I have seen that some time ago you were talking about creating an improvement for the module including minutes to be more accurate.
If you finally create it can you share it, I am creating a magicmirror and I would like to put this module that I love, but I need the minutes :).

Thanks in advance!

**Comment by ngnijland** [comment]
Hi @volobig!

Thanks for showing interest in this module! I do not have anything planned related to minutes. I saw that @pierrephi created an issue explaining that he was working on adding support for showing minutes using dots outside the four corners of the clock. He either didn't finish the feature or didn't open a PR to this repository for it.

Feel free to open a new PR adding this functionality or maybe check [his branch](https://github.com/pierrephi/MMM-text-clock/tree/feature/minutes), copy those changes and open a PR with those changes. If you go for the latter make sure to somehow give credit to @pierrephi, either in the code or in another way.

I hope this helps!
