### ISSUE TITLE
MMM-text-clock not installing / starting

### ISSUE THREAD

**Issue by 1Cedric1** [ngnijland/MMM-text-clock#37]
Hello @ngnijland 
I wanted to try your great text-clock module, but after copying the git files and updating the config file, nothing happens.. is an npm installation or whatever needed?
Thank you for your interest and have a great afternoon.
Kind regards,
Cédric

**Comment by ngnijland** [comment]
Hi @1Cedric1!

Cool that you're trying the clock module! There is no npm installation needed. It should work according to the instructions in the README.

Do you see any error messages that are related to this module either in the terminal or in the browser console?

Regards,
Niek

**Comment by 1Cedric1** [comment]
Hello @ngnijland,
and thank you for your reply.
I do not see anything related to your module in the errog log file
![Capture d’écran 2024-09-05 à 18 18 48](https://github.com/user-attachments/assets/64a17bfc-1be1-4158-9571-e13c02aa7f90)

![Capture d’écran 2024-09-05 à 18 21 53](https://github.com/user-attachments/assets/d422240e-c3ba-4036-88db-bfb782076549)


here my config file
![Capture d’écran 2024-09-05 à 18 16 32](https://github.com/user-attachments/assets/6167eb62-9a20-493a-86db-bbd7e8137e45)

and how it looks like on the mirror : the module is not appearing.

![Capture d’écran 2024-09-05 à 18 17 04](https://github.com/user-attachments/assets/322738c5-e852-4603-9aab-f56c26e1fb92)

My mirror is not so old, as I reinstalled it at the beginning of the summer.

I really do not understand.

the mirror is running on a Raspberry 4 and all other modules work well.

do you maybe have an idea?

**Comment by 1Cedric1** [comment]
Oh, I just found the problem, it had with the language which was not recognised. 

Evertithing OK now, thank you very much for your work and your help.

Very much appreciated.

All the best.

**Comment by ngnijland** [comment]
Glad to hear that it worked out for you! Enjoy your mirror setup 👏
