### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by 1Cedric1** [ngnijland/MMM-text-clock#38]
Hello,

i have found a translation issue in DE.

Text in EN is ok (6 o'clock)

![IMG_20240912_175906_HDR.jpg](https://github.com/user-attachments/assets/9c2c29e7-47f8-4913-94bc-94a1d1fefecf)

But false um DE

![IMG_20240912_175942_HDR.jpg](https://github.com/user-attachments/assets/e541f7f9-f8ae-414a-8174-7c6a1c7d8d18)

It should be : 'Es ist sechs Uhr' instead of 'Es ist Uhr sechs'.

Hope it will help ro make your module even more great!

Kind regards

Cédric

**Comment by pierrephi** [comment]
Problem resolved

**Comment by 1Cedric1** [comment]
Dear @pierrephi ,
thank you for your message.
I reinstalled you module, but the issue is still appearing on the screen.
Is there another way to install your module ?

**Comment by pierrephi** [comment]
Make sure you have the latest version

```
cd MMM-text-clock
git pull
npm install
```
and restart MM

**Comment by pierrephi** [comment]
![image](https://github.com/user-attachments/assets/38d0ee18-ee15-411f-b5c1-5e7d80a1b0ab)

**Comment by 1Cedric1** [comment]
Ok perfect, it works! Thank you very much!

**Comment by pierrephi** [comment]
👍😅
