### ISSUE TITLE
hour rounding problem from 57 - 59 minutes

### ISSUE THREAD

**Issue by T-Git-64** [ngnijland/MMM-text-clock#46]
First of all,  i would like to thank you for the module - I have been running a mirror for a while now.  It is fun and the Text clock is something not a lot of people have seen before,  so it helps to draw attention to my  mirror.

I recently updated my MMM-text-clock module and noticed some nice new features compared to my old outdated module.  
But I also saw a bug that I have previously found and fixed.  thought I would share the fix with you. 
When not using the show minutes indicator dots,  the rounding starting at 57 minutes seems to jump back to the previous hour.

In other words,  
at  this time...the display shows:
9:47 - 9:52 am .... "It is Ten to Ten". 
9:53 - 9:57 am, ... "It is Five to Ten",
9:58 - 9:59 am ..."it is nine o'clock",
10:00 - "it is ten o'clock"

I think the main problem is from when you added the minute indicators,  and decide what to display based on the  "normalizedMinutes".  I think it would be ok if you did that when you only have one bit of code to do the rounding,  but now that you have two (to "immediately lower 5 minutes" or to "closest 5 minutes"),  then you must also have two different displayHour calculations to match.

I don't know much about how GIT works and to submit changes - so here is the new code I came up with for the displayTime function that seems to correct the problem.

The main changes:
- added a declaration for displayHour near the top of the code - using "const" inside the scope where it was won't work because we need to reference it outside of the if or else scopes.
- removed the single displayHour calculation based on "normalizedMinutes",  
- added two other displayHour calculations based on the value of "minutes".  That way the criteria can fit the type of rounding you do in each algorithm

I hope this helps.
Thank you again for this module.

Cheers,
T.

  /*
   * Centralise the time display function in a manner that suits most languages
   * This function returns
   *   morning: a boolean which replicates the behaviour of AM/PM in english
   *   hours_to_display: the hour to display 12h format (past 30' on the hour = the next hour)
   *   minutes_to_display: in 5 minute increment, negative is "to the hour", positive is "past the hour"
   */
  displayTime: function (time) {
    const hours = time.getHours();
    const minutes = time.getMinutes();
    let displayHour = 0;
    
    let normalizedMinutes = 0;
    if (this.showMinutesIndicators && !this.compact) {
      // Rounding to the immediately lower 5 minute increment
      if (minutes >= 5 && minutes < 10) {
        normalizedMinutes = 5;
      } else if (minutes >= 55 && minutes <= 59) {
        normalizedMinutes = -5;
      } else if (minutes >= 10 && minutes < 15) {
        normalizedMinutes = 10;
      } else if (minutes >= 50 && minutes < 55) {
        normalizedMinutes = -10;
      } else if (minutes >= 15 && minutes < 20) {
        normalizedMinutes = 15;
      } else if (minutes >= 45 && minutes < 50) {
        normalizedMinutes = -15;
      } else if (minutes >= 20 && minutes < 25) {
        normalizedMinutes = 20;
      } else if (minutes >= 40 && minutes < 45) {
        normalizedMinutes = -20;
      } else if (minutes >= 25 && minutes < 30) {
        normalizedMinutes = 25;
      } else if (minutes >= 35 && minutes < 40) {
        normalizedMinutes = -25;
      } else if (minutes >= 30 && minutes < 35) {
        normalizedMinutes = 30;
      }
      
    // If displaying minutes to the hour : bump the hour one notch
    displayHour = (minutes >=  35 ? hours + 1 : hours) % 24;
    
    }
    
    else 
    {
      // Original rounding algorithm, rounding to the closest 5 minute increment
      
      if (minutes >= 3 && minutes <= 7) {
        normalizedMinutes = 5;
      } else if (minutes >= 53 && minutes <= 57) {
        normalizedMinutes = -5;
      } else if (minutes >= 8 && minutes <= 12) {
        normalizedMinutes = 10;
      } else if (minutes >= 48 && minutes <= 52) {
        normalizedMinutes = -10;
      } else if (minutes >= 13 && minutes <= 17) {
        normalizedMinutes = 15;
      } else if (minutes >= 43 && minutes <= 47) {
        normalizedMinutes = -15;
      } else if (minutes >= 18 && minutes <= 22) {
        normalizedMinutes = 20;
      } else if (minutes >= 38 && minutes <= 42) {
        normalizedMinutes = -20;
      } else if (minutes >= 23 && minutes <= 27) {
        normalizedMinutes = 25;
      } else if (minutes >= 33 && minutes <= 37) {
        normalizedMinutes = -25;
      } else if (minutes >= 28 && minutes <= 32) {
        normalizedMinutes = 30;
      }
      // If displaying minutes to the hour : bump the hour one notch
      displayHour = (minutes >=  33 ? hours + 1 : hours) % 24;

    }

    // use 12 hour format
    const normalizedHour = displayHour > 12 ? displayHour - 12 : displayHour;
    const minutesFromMidnight = hours * 60 + minutes;
    const morning =
      this.showMinutesIndicators && !this.compact
        ? minutesFromMidnight <= 750 && minutesFromMidnight >= 35
        : minutesFromMidnight < 753 && minutesFromMidnight >= 33;
    
    return {
      morning: morning,
      hours_to_display: normalizedHour,
      minutes_to_display: normalizedMinutes,
      hours: hours,
      minutes: minutes,
    };
  }

**Comment by pierrephi** [comment]
Thanks for reporting I did indeed do something wrong here, will fix it shortly

**Comment by pierrephi** [comment]
All done!
